FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package.json
COPY apps/web/package.json apps/web/package.json
RUN npm install --workspaces
COPY . .
WORKDIR /app/apps/web
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/apps/web/dist/web/browser /usr/share/nginx/html
